In [1]:
import torch
from torch import nn

torch.cuda.device_count()

1

In [2]:
def try_gpu(i=0):  
    """如果存在，则返回gpu(i)，否则返回cpu()。"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():  
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]。"""
    devices = [
        torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [3]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [5]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [9]:
Y = torch.rand(2, 3, device=try_gpu(0))
Y

tensor([[0.4341, 0.9495, 0.3200],
        [0.8021, 0.7107, 0.2140]], device='cuda:0')

In [10]:
Z = X.cuda(0)
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [11]:
Y + Z

tensor([[1.4341, 1.9495, 1.3200],
        [1.8021, 1.7107, 1.2140]], device='cuda:0')

In [12]:
Z.cuda(0) is Z

True

In [13]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

net(X)

tensor([[1.7507],
        [1.7507]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [14]:
net[0].weight.data.device

device(type='cuda', index=0)